// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: inventories.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InventoryRpc_CheckStock_FullMethodName = "/rpc.InventoryRpc/CheckStock"
)

// InventoryRpcClient is the client API for InventoryRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The greeting service definition.
type InventoryRpcClient interface {
	// Sends a greeting
	CheckStock(ctx context.Context, in *Item, opts ...grpc.CallOption) (*ItemStock, error)
}

type inventoryRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewInventoryRpcClient(cc grpc.ClientConnInterface) InventoryRpcClient {
	return &inventoryRpcClient{cc}
}

func (c *inventoryRpcClient) CheckStock(ctx context.Context, in *Item, opts ...grpc.CallOption) (*ItemStock, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ItemStock)
	err := c.cc.Invoke(ctx, InventoryRpc_CheckStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InventoryRpcServer is the server API for InventoryRpc service.
// All implementations must embed UnimplementedInventoryRpcServer
// for forward compatibility.
//
// The greeting service definition.
type InventoryRpcServer interface {
	// Sends a greeting
	CheckStock(context.Context, *Item) (*ItemStock, error)
	mustEmbedUnimplementedInventoryRpcServer()
}

// UnimplementedInventoryRpcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInventoryRpcServer struct{}

func (UnimplementedInventoryRpcServer) CheckStock(context.Context, *Item) (*ItemStock, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckStock not implemented")
}
func (UnimplementedInventoryRpcServer) mustEmbedUnimplementedInventoryRpcServer() {}
func (UnimplementedInventoryRpcServer) testEmbeddedByValue()                      {}

// UnsafeInventoryRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InventoryRpcServer will
// result in compilation errors.
type UnsafeInventoryRpcServer interface {
	mustEmbedUnimplementedInventoryRpcServer()
}

func RegisterInventoryRpcServer(s grpc.ServiceRegistrar, srv InventoryRpcServer) {
	// If the following call pancis, it indicates UnimplementedInventoryRpcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InventoryRpc_ServiceDesc, srv)
}

func _InventoryRpc_CheckStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Item)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryRpcServer).CheckStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryRpc_CheckStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryRpcServer).CheckStock(ctx, req.(*Item))
	}
	return interceptor(ctx, in, info, handler)
}

// InventoryRpc_ServiceDesc is the grpc.ServiceDesc for InventoryRpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InventoryRpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.InventoryRpc",
	HandlerType: (*InventoryRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckStock",
			Handler:    _InventoryRpc_CheckStock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inventories.proto",
}
