// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: inventories.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=itemId,proto3" json:"itemId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_inventories_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_inventories_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_inventories_proto_rawDescGZIP(), []int{0}
}

func (x *Item) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

type ItemStock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=itemId,proto3" json:"itemId,omitempty"`
	Stock         int32                  `protobuf:"varint,2,opt,name=stock,proto3" json:"stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemStock) Reset() {
	*x = ItemStock{}
	mi := &file_inventories_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemStock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemStock) ProtoMessage() {}

func (x *ItemStock) ProtoReflect() protoreflect.Message {
	mi := &file_inventories_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemStock.ProtoReflect.Descriptor instead.
func (*ItemStock) Descriptor() ([]byte, []int) {
	return file_inventories_proto_rawDescGZIP(), []int{1}
}

func (x *ItemStock) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *ItemStock) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

var File_inventories_proto protoreflect.FileDescriptor

const file_inventories_proto_rawDesc = "" +
	"\n" +
	"\x11inventories.proto\x12\x03rpc\"\x1e\n" +
	"\x04Item\x12\x16\n" +
	"\x06itemId\x18\x01 \x01(\tR\x06itemId\"9\n" +
	"\tItemStock\x12\x16\n" +
	"\x06itemId\x18\x01 \x01(\tR\x06itemId\x12\x14\n" +
	"\x05stock\x18\x02 \x01(\x05R\x05stock29\n" +
	"\fInventoryRpc\x12)\n" +
	"\n" +
	"CheckStock\x12\t.rpc.Item\x1a\x0e.rpc.ItemStock\"\x00B7\n" +
	"\x1bio.grpc.examples.helloworldB\x0fHelloWorldProtoP\x01Z\x05./rpcb\x06proto3"

var (
	file_inventories_proto_rawDescOnce sync.Once
	file_inventories_proto_rawDescData []byte
)

func file_inventories_proto_rawDescGZIP() []byte {
	file_inventories_proto_rawDescOnce.Do(func() {
		file_inventories_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inventories_proto_rawDesc), len(file_inventories_proto_rawDesc)))
	})
	return file_inventories_proto_rawDescData
}

var file_inventories_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_inventories_proto_goTypes = []any{
	(*Item)(nil),      // 0: rpc.Item
	(*ItemStock)(nil), // 1: rpc.ItemStock
}
var file_inventories_proto_depIdxs = []int32{
	0, // 0: rpc.InventoryRpc.CheckStock:input_type -> rpc.Item
	1, // 1: rpc.InventoryRpc.CheckStock:output_type -> rpc.ItemStock
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_inventories_proto_init() }
func file_inventories_proto_init() {
	if File_inventories_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inventories_proto_rawDesc), len(file_inventories_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inventories_proto_goTypes,
		DependencyIndexes: file_inventories_proto_depIdxs,
		MessageInfos:      file_inventories_proto_msgTypes,
	}.Build()
	File_inventories_proto = out.File
	file_inventories_proto_goTypes = nil
	file_inventories_proto_depIdxs = nil
}
