// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: inventories-rpc/inventories.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InventoryRpc_CheckStock_FullMethodName   = "/rpc.InventoryRpc/CheckStock"
	InventoryRpc_ReserveStock_FullMethodName = "/rpc.InventoryRpc/ReserveStock"
	InventoryRpc_ReleaseStock_FullMethodName = "/rpc.InventoryRpc/ReleaseStock"
)

// InventoryRpcClient is the client API for InventoryRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InventoryRpcClient interface {
	CheckStock(ctx context.Context, in *CheckStockRequest, opts ...grpc.CallOption) (*ItemStock, error)
	ReserveStock(ctx context.Context, in *ReserveStockRequest, opts ...grpc.CallOption) (*ReserverResponse, error)
	ReleaseStock(ctx context.Context, in *ReleaseStockRequest, opts ...grpc.CallOption) (*ReleaseResponse, error)
}

type inventoryRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewInventoryRpcClient(cc grpc.ClientConnInterface) InventoryRpcClient {
	return &inventoryRpcClient{cc}
}

func (c *inventoryRpcClient) CheckStock(ctx context.Context, in *CheckStockRequest, opts ...grpc.CallOption) (*ItemStock, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ItemStock)
	err := c.cc.Invoke(ctx, InventoryRpc_CheckStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryRpcClient) ReserveStock(ctx context.Context, in *ReserveStockRequest, opts ...grpc.CallOption) (*ReserverResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReserverResponse)
	err := c.cc.Invoke(ctx, InventoryRpc_ReserveStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryRpcClient) ReleaseStock(ctx context.Context, in *ReleaseStockRequest, opts ...grpc.CallOption) (*ReleaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseResponse)
	err := c.cc.Invoke(ctx, InventoryRpc_ReleaseStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InventoryRpcServer is the server API for InventoryRpc service.
// All implementations must embed UnimplementedInventoryRpcServer
// for forward compatibility.
type InventoryRpcServer interface {
	CheckStock(context.Context, *CheckStockRequest) (*ItemStock, error)
	ReserveStock(context.Context, *ReserveStockRequest) (*ReserverResponse, error)
	ReleaseStock(context.Context, *ReleaseStockRequest) (*ReleaseResponse, error)
	mustEmbedUnimplementedInventoryRpcServer()
}

// UnimplementedInventoryRpcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInventoryRpcServer struct{}

func (UnimplementedInventoryRpcServer) CheckStock(context.Context, *CheckStockRequest) (*ItemStock, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckStock not implemented")
}
func (UnimplementedInventoryRpcServer) ReserveStock(context.Context, *ReserveStockRequest) (*ReserverResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReserveStock not implemented")
}
func (UnimplementedInventoryRpcServer) ReleaseStock(context.Context, *ReleaseStockRequest) (*ReleaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReleaseStock not implemented")
}
func (UnimplementedInventoryRpcServer) mustEmbedUnimplementedInventoryRpcServer() {}
func (UnimplementedInventoryRpcServer) testEmbeddedByValue()                      {}

// UnsafeInventoryRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InventoryRpcServer will
// result in compilation errors.
type UnsafeInventoryRpcServer interface {
	mustEmbedUnimplementedInventoryRpcServer()
}

func RegisterInventoryRpcServer(s grpc.ServiceRegistrar, srv InventoryRpcServer) {
	// If the following call pancis, it indicates UnimplementedInventoryRpcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InventoryRpc_ServiceDesc, srv)
}

func _InventoryRpc_CheckStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckStockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryRpcServer).CheckStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryRpc_CheckStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryRpcServer).CheckStock(ctx, req.(*CheckStockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryRpc_ReserveStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReserveStockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryRpcServer).ReserveStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryRpc_ReserveStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryRpcServer).ReserveStock(ctx, req.(*ReserveStockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryRpc_ReleaseStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseStockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryRpcServer).ReleaseStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryRpc_ReleaseStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryRpcServer).ReleaseStock(ctx, req.(*ReleaseStockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InventoryRpc_ServiceDesc is the grpc.ServiceDesc for InventoryRpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InventoryRpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.InventoryRpc",
	HandlerType: (*InventoryRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckStock",
			Handler:    _InventoryRpc_CheckStock_Handler,
		},
		{
			MethodName: "ReserveStock",
			Handler:    _InventoryRpc_ReserveStock_Handler,
		},
		{
			MethodName: "ReleaseStock",
			Handler:    _InventoryRpc_ReleaseStock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inventories-rpc/inventories.proto",
}
